import React, { useMemo, useState } from "react";
import "./App.css";
const generateLogoPath = (clubName: string) => {
  const cleanName = clubName
    .toLowerCase()
    .replace(/[^\w\s]/g, "") // remove punctuation
    .replace(/\s+/g, "-"); // replace spaces with dash
  return `/assets/logos/${cleanName}.png`;
};

interface Club {
  id: string;
  name: string;
  city: string;
  state: string;
  location: string;
  night: string;
  caller_cuer?: string;
  time: string;
  level: string;
  telephone: string;
  email: string;
  facebook: string;
  website: string;
  logo?: string;
}

/**
 * State colors (background) and button border colors.
 * Buttons use the background color and have a border color defined below.
 */
const stateColors: { [key: string]: string } = {
  WA: "#F5C45C",
  SA: "#ED174C",
  NSW: "#CBEDFD",
  TAS: "#A10035",
  ACT: "#FFCE00",
  VIC: "#001F7E",
  QLD: "#7D0096",
};

/**
 * Button border colors per your request
 */
const stateBorderColors: { [key: string]: string } = {
  WA: "#000000", // black
  SA: "#E17000", // gold
  VIC: "#C0C0C0", // silver
  NSW: "#FF0000", // red
  QLD: "#006A4E", // bottle green
  ACT: "#012B88", // resolution blue
  TAS: "#228B22", // green (suggested)
};

/**
 * Raw club data (as requested). NOTE: logos are set programmatically later to /assets/logos/{ID}.png
 */
const clubsRaw: Club[] = [
  // core demo & provided club data (keeps the data you gave in your messages)
  // ---------------------------------------------------------------------
  {
    id: "SA-001",
    name: "Adelaide Dancers",
    city: "Adelaide",
    state: "SA",
    location: "Town Hall, Adelaide",
    night: "Saturday",
    caller_cuer: "Jane Smith",
    time: "7:00 PM - 9:30 PM",
    level: "Mainstream",
    telephone: "08 9876 5432",
    email: "adelaidedancers@example.com",
    facebook: "https://www.facebook.com/adelaidedancers",
    website: "https://www.adelaidedancers.com",
    logo: "",
  },
  {
    id: "NSW-001",
    name: "Sydney Square Club",
    city: "Sydney",
    state: "NSW",
    location: "Sydney Community Hall",
    night: "Thursday",
    caller_cuer: "Alice Brown",
    time: "7:30 PM - 10:00 PM",
    level: "All Levels",
    telephone: "02 1234 5678",
    email: "sydneysquare@example.com",
    facebook: "https://www.facebook.com/sydneysquareclub",
    website: "https://www.sydneysquareclub.com",
    logo: "",
  },
  {
    id: "TAS-001",
    name: "Hobart Hoedowners",
    city: "Hobart",
    state: "TAS",
    location: "Hobart Hall",
    night: "Wednesday",
    caller_cuer: "Tom Green",
    time: "7:00 PM - 9:30 PM",
    level: "Mainstream",
    telephone: "03 1234 5678",
    email: "hobarthoedowners@example.com",
    facebook: "https://www.facebook.com/hobarthoedowners",
    website: "https://www.hobarthoedowners.com",
    logo: "",
  },
  {
    id: "ACT-001",
    name: "Kerr-Ly-Qs",
    city: "Canberra",
    state: "ACT",
    location: "Canberra Community Centre",
    night: "Tuesday",
    caller_cuer: "Allen Kerr",
    time: "7:30 PM - 10:00 PM",
    level: "All Levels",
    telephone: "02 8765 4321",
    email: "kerrlyqs@example.com",
    facebook: "https://www.facebook.com/kerrlyqs",
    website: "https://www.kerrlyqs.com",
    logo: "",
  },

  // --- WA clubs ---
  {
    id: "WA-001",
    name: "Cloverwest",
    city: "Shenton Park",
    state: "WA",
    location: "Shenton Park Community Centre, 240 Onslow Road, Shenton Park",
    night: "Monday",
    caller_cuer: "Kevin Fitzgerald",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "+61 413 156 192",
    email: "fitz27@bigpond.com",
    facebook: "https://www.facebook.com/cloverwest.square.dance/about/",
    website: "",
    logo: "",
  },
  {
    id: "WA-002",
    name: "Bunbury Square Dancers",
    city: "Eaton / Bunbury",
    state: "WA",
    location: "Eaton Family Centre, 4 Charterhouse Street, Eaton",
    night: "Monday",
    caller_cuer: "",
    time: "8:00pm",
    level: "Mainstream & Learning Plus",
    telephone: "+61 413 156 192",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "WA-003",
    name: "Kiwilers",
    city: "Como",
    state: "WA",
    location: "P & C Hall, Cnr Coode & Thelma Street, Como",
    night: "Monday (Plus) & Thursday (Advanced)",
    caller_cuer: "Richard Muir",
    time: "7:30pm (Mon Plus) / 7:30pm (Thu Advanced 1&2)",
    level: "Plus / Advanced",
    telephone: "+61 8 9474 5485",
    email: "",
    facebook: "https://www.facebook.com/Kiwilers",
    website: "",
    logo: "",
  },
  {
    id: "WA-004",
    name: "Northern Stars",
    city: "Muchea",
    state: "WA",
    location: "Muchea Recreation Centre, 48 Archibald Street, Muchea",
    night: "Monday",
    caller_cuer: "Mp3 club",
    time: "7:30pm",
    level: "SSD & Mainstream",
    telephone: "+61 407 389 948",
    email: "northernstars.squaredance@outlook.com",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "WA-005",
    name: "Riverside",
    city: "Bentley",
    state: "WA",
    location: "Bentley Community Centre / Bentley Hub, Nyamup Way, Bentley",
    night: "Monday",
    caller_cuer: "",
    time: "8:00pm",
    level: "Mainstream",
    telephone: "+61 419 563 375",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "WA-006",
    name: "Wheatbelt Squares",
    city: "Goomalling",
    state: "WA",
    location: "Goomalling Senior Citizens Centre, Cnr Quinlan & Lockyer Street, Goomalling",
    night: "Alternate Mondays",
    caller_cuer: "Robert Dew",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "+61 429 962 012",
    email: "",
    facebook: "https://www.facebook.com/profile.php?id=100058285523603",
    website: "",
    logo: "",
  },
  {
    id: "WA-007",
    name: "Greenfinches",
    city: "Hamersley",
    state: "WA",
    location: "Hamersley Recreation Centre, 20 Belvedere Road, Hamersley",
    night: "Tuesday (Rounds 1st/3rd/5th; Plus 2nd/4th)",
    caller_cuer: "Steve Turner, Jim Buckingham, Greg Fawell",
    time: "8:00pm",
    level: "Mainstream / Rounds / Plus",
    telephone: "+61 419 900 441",
    email: "longwood@iinet.net.au",
    facebook: "https://www.facebook.com/groups/greenfinches",
    website: "",
    logo: "",
  },
  {
    id: "WA-008",
    name: "Ups 'N' Downers",
    city: "Gosnells",
    state: "WA",
    location: "All Saints Anglican Church Hall, Cnr Hicks & Dorothy Street, Gosnells",
    night: "Tuesday",
    caller_cuer: "Keith Lethbridge",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "+61 407 442 957",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "WA-009",
    name: "Dolphin Dancers",
    city: "Mandurah",
    state: "WA",
    location: "Mandurah Bowling Club, 89 Allnut Street, Mandurah",
    night: "Wednesday (daytime sessions listed)",
    caller_cuer: "Natalie Scott / Paul Long",
    time: "1:15pm – 3:15pm",
    level: "Mainstream",
    telephone: "+61 411 449 344",
    email: "dolphin.dancers@outlook.com",
    facebook: "https://www.facebook.com/dolphinsquaredancers",
    website: "",
    logo: "",
  },
  {
    id: "WA-010",
    name: "Dianella Rangers",
    city: "Joondanna",
    state: "WA",
    location: "St Peter and Emmaus Church Hall, 56 Green Street, Joondanna",
    night: "Wednesday (Mainstream) & Thursday (Rounds morning)",
    caller_cuer: "Kevin Fitzgerald / Marilyn Van Sambeeck",
    time: "7:30pm (Wed Mainstream) / 10:00am–12:00pm (Thu Rounds)",
    level: "Mainstream / Rounds",
    telephone: "+61 8 9302 4779",
    email: "",
    facebook: "https://www.facebook.com/dianellarangerssdc",
    website: "https://www.dianellarangerssdc.com/",
    logo: "",
  },
  {
    id: "WA-011",
    name: "Jay Gees Squares",
    city: "Bunbury",
    state: "WA",
    location: "St Augustine’s Uniting Church Hall, 119 Mangles Street, Bunbury",
    night: "Wednesday",
    caller_cuer: "Jeff Garbutt",
    time: "7:30pm–9:30pm",
    level: "SSD+ / Mainstream",
    telephone: "+61 427 935 674",
    email: "jeffgarbutt@gmail.com",
    facebook: "https://www.facebook.com/JayGeesSquares/about/",
    website: "https://jeffgarbutt.wixsite.com/jaygees",
    logo: "",
  },
  {
    id: "WA-012",
    name: "JoKing Cloggers",
    city: "High Wycombe / Gosnells",
    state: "WA",
    location: "Cyril Road Community Centre (Thu) / Gosnells RSL (Sat)",
    night: "Thursday & Saturday",
    caller_cuer: "",
    time: "7:00pm–9:00pm (Thu) / 10:30am–12:00pm (Sat)",
    level: "Clogging – all levels",
    telephone: "+61 417 943 640 / +61 421 589 501",
    email: "jokingcloggerswa@gmail.com",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "WA-013",
    name: "White Gum Valley (WgV Squares)",
    city: "Rossmoyne / Perth",
    state: "WA",
    location: "Rossmoyne Bowling Club, 35 Tuscon Street, Rossmoyne",
    night: "Thursday",
    caller_cuer: "",
    time: "7:45pm",
    level: "Mainstream",
    telephone: "+61 478 559 554",
    email: "wgvsquares@gmail.com",
    facebook: "https://www.facebook.com/profile.php?id=100066477955147",
    website: "",
    logo: "",
  },
  {
    id: "WA-014",
    name: "Allemander Squares",
    city: "Currambine",
    state: "WA",
    location: "Currambine Community Centre, 64 Delamere Avenue, Currambine",
    night: "Thursday",
    caller_cuer: "Jim Buckingham",
    time: "7:00pm–9:00pm",
    level: "Beginners / Mainstream / Plus (if enough dancers)",
    telephone: "+61 418 948 823",
    email: "jimsgr8trax2@gmail.com",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "WA-015",
    name: "Happy Wanderers",
    city: "High Wycombe",
    state: "WA",
    location: "Cyril Road Community Centre, 58 Cyril Road, High Wycombe",
    night: "Friday",
    caller_cuer: "Kevin Kelly",
    time: "7:00pm (Plus) / 8:00pm (Mainstream)",
    level: "Plus & Mainstream",
    telephone: "+61 427 161 159",
    email: "happywandererssdc@gmail.com",
    facebook: "https://www.facebook.com/groups/1279808272116694",
    website: "",
    logo: "",
  },
  {
    id: "WA-016",
    name: "Swan Valley Squares",
    city: "Dayton",
    state: "WA",
    location: "Dayton Community Centre, 211 Arthur Street, Dayton",
    night: "Friday",
    caller_cuer: "Greg Fawell",
    time: "7:30pm (Plus) / 8:00pm (Mainstream)",
    level: "Plus & Mainstream",
    telephone: "+61 417 912 241",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "WA-017",
    name: "Gidgegannup Square Dance Club",
    city: "Gidgegannup",
    state: "WA",
    location: "Gidgegannup Showgrounds Hall, Old Toodyay Road, Gidgegannup",
    night: "2nd & 4th Saturday",
    caller_cuer: "",
    time: "8:00pm",
    level: "Mainstream",
    telephone: "+61 417 092 309",
    email: "",
    facebook: "https://www.facebook.com/groups/581177512415769",
    website: "",
    logo: "",
  },
  {
    id: "WA-018",
    name: "P & R Rounds",
    city: "Bassendean",
    state: "WA",
    location: "Bassendean RSL Hall / local seniors centre",
    night: "Saturday",
    caller_cuer: "",
    time: "12:00pm (Seniors) / 1:00pm (Intermediate) / 2:00pm (Beginners)",
    level: "Rounds / Intermediate / Beginners",
    telephone: "+61 418 926 202",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },

  // QLD Clubs
  {
    id: "QLD-001",
    name: "Suncoasters Square Dance Club",
    city: "Buderim",
    state: "QLD",
    location: "Sunshine Coast Square Dance Centre, Buderim, 260 Dixon Road",
    night: "1st, 3rd & 5th Saturdays",
    caller_cuer: "",
    time: "",
    level: "Basics to A",
    telephone: "",
    email: "scsdc260dixon@outlook.com",
    facebook: "https://www.facebook.com/Suncoasters",
    website: "https://www.suncoasters.com.au/",
    logo: "",
  },
  {
    id: "QLD-002",
    name: "UpBeat Chaos",
    city: "Brisbane",
    state: "QLD",
    location: "",
    night: "Monday",
    caller_cuer: "",
    time: "7:00-9:00pm",
    level: "Plus",
    telephone: "",
    email: "",
    facebook: "",
    website: "https://www.upbeatchaos.com",
    logo: "",
  },
  {
    id: "QLD-003",
    name: "Kay's Plus",
    city: "Graceville / Brisbane region",
    state: "QLD",
    location: "",
    night: "1st & 3rd Sundays",
    caller_cuer: "",
    time: "1:00-3:00pm (teaching Plus) / 3:00-5:00pm (Extended Plus)",
    level: "Plus",
    telephone: "",
    email: "",
    facebook: "",
    website: "https://www.kaysclubs.com/",
    logo: "",
  },
  {
    id: "QLD-004",
    name: "Northside Promenaders",
    city: "Zillmere (Brisbane Northside)",
    state: "QLD",
    location: "30 Seeney St., Zillmere, QLD",
    night: "Thursday",
    caller_cuer: "",
    time: "7:30pm (Mainstream) / 7:00-7:30 warmup Plus",
    level: "Plus / Mainstream",
    telephone: "0413 017 778",
    email: "northprom@gmail.com",
    facebook: "https://www.facebook.com/zillmere",
    website: "http://northsidepromenaderssdc.weebly.com/",
    logo: "",
  },
  {
    id: "QLD-005",
    name: "Gumdale Grandsliders",
    city: "Gumdale",
    state: "QLD",
    location: "",
    night: "",
    caller_cuer: "",
    time: "",
    level: "",
    telephone: "",
    email: "",
    facebook: "",
    website: "http://gumdalegrandsliders.blogspot.com",
    logo: "",
  },
  {
    id: "QLD-006",
    name: "Hervey Bay Square Dance Club",
    city: "Hervey Bay",
    state: "QLD",
    location: "459 Boat Harbour Dr, Torquay",
    night: "",
    caller_cuer: "",
    time: "",
    level: "",
    telephone: "0404 655271",
    email: "",
    facebook: "",
    website: "https://squaredancingherveybay.com.au/",
    logo: "/logos/Hervey%20Bay%20Square%20Dance%20Club.png",
  },
  {
    id: "QLD-007",
    name: "E.Z. Squares",
    city: "Caboolture",
    state: "QLD",
    location: "",
    night: "",
    caller_cuer: "",
    time: "",
    level: "",
    telephone: "",
    email: "",
    facebook: "",
    website: "https://ezsquarescaboolture.weebly.com/",
    logo: "",
  },
  {
    id: "QLD-008",
    name: "Wavell Whirlaways",
    city: "Wavell Heights",
    state: "QLD",
    location: "62 Flower Street, Northgate, Brisbane",
    night: "",
    caller_cuer: "",
    time: "",
    level: "",
    telephone: "0418 724 636",
    email: "",
    facebook: "https://www.facebook.com/wavellwhirlawaysquaredanceclub",
    website: "",
    logo: "",
  },

  // VIC Clubs
  {
    id: "VIC-001",
    name: "Aurora A's",
    city: "Donvale",
    state: "VIC",
    location: "Donvale Presbyterian Church Hall, 101 Mitcham Rd, Donvale",
    night: "Tuesday",
    caller_cuer: "",
    time: "7:30pm – 10:00pm",
    level: "Mainstream / Plus",
    telephone: "+61 3 9874 7653",
    email: "",
    facebook: "",
    website: "http://www.squaredance.org.au/aurora",
    logo: "",
  },
  {
    id: "VIC-002",
    name: "Bayside Squares",
    city: "Mordialloc",
    state: "VIC",
    location: "St Jude’s Church Hall, 27 Albert St, Mordialloc",
    night: "Friday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "+61 3 9580 0605",
    email: "",
    facebook: "https://www.facebook.com/BaysideSquares/",
    website: "",
    logo: "",
  },
  {
    id: "VIC-003",
    name: "Diamond Valley Squares",
    city: "Greensborough",
    state: "VIC",
    location: "Greensborough Masonic Hall, Ester St, Greensborough",
    night: "Wednesday",
    caller_cuer: "",
    time: "7:30pm – 10:00pm",
    level: "Mainstream / Plus",
    telephone: "+61 3 9435 3308",
    email: "",
    facebook: "",
    website: "http://www.squaredance.org.au/diamondvalley",
    logo: "",
  },
  {
    id: "VIC-004",
    name: "Nunawading T-Squares",
    city: "Nunawading",
    state: "VIC",
    location: "Uniting Church Hall, 355 Whitehorse Rd, Nunawading",
    night: "Thursday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "+61 3 9802 5087",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "VIC-005",
    name: "Southern Cross Plus",
    city: "Burwood East",
    state: "VIC",
    location: "Burwood Heights Uniting Church Hall, 347 Blackburn Rd, Burwood East",
    night: "Monday",
    caller_cuer: "Howard Cockburn",
    time: "7:30pm – 10:00pm",
    level: "Plus",
    telephone: "+61 3 9803 1626",
    email: "",
    facebook: "https://www.facebook.com/groups/103790413107844",
    website: "",
    logo: "",
  },
  {
    id: "VIC-006",
    name: "Stradbroke Squares",
    city: "Sale",
    state: "VIC",
    location: "Guthridge Primary School Hall, Guthridge Parade, Sale",
    night: "Thursday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "+61 3 5144 3428",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "VIC-007",
    name: "Whitehorse Squares",
    city: "Nunawading",
    state: "VIC",
    location: "Nunawading Uniting Church Hall, 355 Whitehorse Rd, Nunawading",
    night: "Tuesday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "+61 3 9878 3132",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "VIC-008",
    name: "Essendon Squares",
    city: "Essendon",
    state: "VIC",
    location: "Uniting Church Hall, 132 Keilor Rd, Essendon",
    night: "Wednesday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "+61 3 9337 1234",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "VIC-009",
    name: "Waverley Squares",
    city: "Glen Waverley",
    state: "VIC",
    location: "Waverley Community Hall, Miller Cres, Glen Waverley",
    night: "Thursday",
    caller_cuer: "",
    time: "7:30pm – 10:00pm",
    level: "Mainstream / Plus",
    telephone: "+61 3 9560 1234",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "VIC-010",
    name: "Eastern 8's",
    city: "Ringwood",
    state: "VIC",
    location: "Ringwood East Senior Citizens Hall, 2A Knaith Rd, Ringwood",
    night: "Tuesday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "+61 3 9870 4567",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "VIC-011",
    name: "Altona Sunset Squares",
    city: "Altona",
    state: "VIC",
    location: "Altona Senior Citizens Hall, 1 Sargood St, Altona",
    night: "Friday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "+61 3 9315 1234",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "VIC-012",
    name: "Golden Squares",
    city: "Bendigo",
    state: "VIC",
    location: "Golden Square Senior Citizens Hall, Bendigo",
    night: "Wednesday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream / Plus",
    telephone: "+61 3 5443 5678",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "VIC-013",
    name: "Border Squares",
    city: "Wodonga",
    state: "VIC",
    location: "Wodonga Senior Citizens Hall, Havelock St, Wodonga",
    night: "Thursday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "+61 2 6024 1234",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "VIC-014",
    name: "Ballarat Squares",
    city: "Ballarat",
    state: "VIC",
    location: "St Andrew’s Uniting Church Hall, Ballarat",
    night: "Friday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "+61 3 5331 1234",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },

  // NSW more (subset repeated / many entries included above but in consistent pattern)
  {
    id: "NSW-002",
    name: "Allemander Square Dance Club",
    city: "Engadine",
    state: "NSW",
    location: "Engadine Community Centre, Old Princes Hwy, Engadine",
    night: "Monday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "0418 644 578",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  
  {
    id: "NSW-004",
    name: "Central Coast Ocean Waves",
    city: "East Gosford",
    state: "NSW",
    location: "East Gosford Progress Hall, Henry Parry Dr, East Gosford",
    night: "Wednesday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream / Plus",
    telephone: "",
    email: "cc.oceanwaves@gmail.com",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-005",
    name: "Knee Deep Squares",
    city: "Lismore",
    state: "NSW",
    location: "Lismore Heights Community Centre, Rous Rd, Lismore Heights",
    night: "Friday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-006",
    name: "Top Cats",
    city: "Blacktown",
    state: "NSW",
    location: "St Andrews Church Hall, Bungarribee Rd, Blacktown",
    night: "Thursday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream / Plus",
    telephone: "",
    email: "",
    facebook: "https://www.facebook.com/TopCatsSquareDance",
    website: "",
    logo: "",
  },
  {
    id: "NSW-007",
    name: "Hillbillies",
    city: "North Ryde",
    state: "NSW",
    location: "North Ryde Community Centre, Coxs Rd, North Ryde",
    night: "Wednesday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream / Plus",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-008",
    name: "Mavericks Square Dance Club",
    city: "Jesmond (Newcastle)",
    state: "NSW",
    location: "Jesmond Neighbourhood Centre, Mordue Parade, Jesmond",
    night: "Friday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-009",
    name: "Redback Squares",
    city: "Tamworth",
    state: "NSW",
    location: "Tamworth Community Centre, Darling St, Tamworth",
    night: "Monday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-010",
    name: "Hunter Valley Squares",
    city: "Maitland",
    state: "NSW",
    location: "Maitland Senior Citizens Centre, High St, Maitland",
    night: "Thursday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-011",
    name: "Shoalhaven Square Dance Club",
    city: "Nowra",
    state: "NSW",
    location: "Nowra School of Arts, Berry St, Nowra",
    night: "Wednesday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-012",
    name: "Sapphire Squares",
    city: "Merimbula",
    state: "NSW",
    location: "Uniting Church Hall, Henwood St, Merimbula",
    night: "Wednesday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-013",
    name: "B-bar-H (Bateau Bay / Peninsula)",
    city: "Bateau Bay",
    state: "NSW",
    location: "Local community hall (check flyer / TAWS listing)",
    night: "Varies (see TAWS/events)",
    caller_cuer: "",
    time: "",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-014",
    name: "Wagga Wagga Square Dance Club",
    city: "Wagga Wagga",
    state: "NSW",
    location: "Local community hall (Wagga region listings)",
    night: "Thursday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-015",
    name: "Port Macquarie Square Dance Club",
    city: "Port Macquarie",
    state: "NSW",
    location: "Port Macquarie community hall (check club page)",
    night: "Tuesday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-016",
    name: "Coffs Harbour Square Dance Club",
    city: "Coffs Harbour",
    state: "NSW",
    location: "Coffs Harbour community hall",
    night: "Wednesday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-017",
    name: "Armidale Squares",
    city: "Armidale",
    state: "NSW",
    location: "Armidale community centre",
    night: "Friday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-018",
    name: "Dubbo Square Dance Club",
    city: "Dubbo",
    state: "NSW",
    location: "Dubbo community hall",
    night: "Monday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-019",
    name: "Woy Woy / Peninsula Ocean Waves",
    city: "Woy Woy",
    state: "NSW",
    location: "Peninsula Community Centre, McMasters Rd, Woy Woy",
    night: "See local listing (TAWS/Active & Healthy)",
    caller_cuer: "",
    time: "",
    level: "Learn to dance / Mainstream",
    telephone: "0429 444 241",
    email: "ccoceanwaves@gmail.com",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-020",
    name: "Illawarra Squares",
    city: "Wollongong",
    state: "NSW",
    location: "Wollongong community hall (check club page)",
    night: "Friday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-021",
    name: "Alstonville / Northern NSW Association (club listings)",
    city: "Alstonville",
    state: "NSW",
    location: "Northern NSW Square Dance Association hall",
    night: "Varies",
    caller_cuer: "",
    time: "",
    level: "",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-022",
    name: "Cessnock Squares",
    city: "Cessnock",
    state: "NSW",
    location: "Cessnock community hall",
    night: "Thursday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-023",
    name: "Forster / Tuncurry Square Dancers",
    city: "Forster",
    state: "NSW",
    location: "Forster Baptist Church Hall (local listing)",
    night: "Wednesday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-024",
    name: "Grafton Square Dancers",
    city: "Grafton",
    state: "NSW",
    location: "Grafton community hall",
    night: "Tuesday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-025",
    name: "Orange Square Dance Club",
    city: "Orange",
    state: "NSW",
    location: "Orange Senior Citizens / community hall",
    night: "Wednesday",
    caller_cuer: "",
    time: "7:30pm",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
  {
    id: "NSW-026",
    name: "New England Squares (Armidale / Tamworth region)",
    city: "New England",
    state: "NSW",
    location: "Regional community hall (check local listing)",
    night: "Varies",
    caller_cuer: "",
    time: "",
    level: "Mainstream",
    telephone: "",
    email: "",
    facebook: "",
    website: "",
    logo: "",
  },
];

const App: React.FC = () => {
  const clubs = useMemo(() => {
    const seen = new Set<string>();
    return clubsRaw
      .filter((c) => {
        if (seen.has(c.id)) return false;
        seen.add(c.id);
        return true;
      })
      .map((c) => ({
        ...c,
        logo: generateLogoPath(c.name), // logo path is now correctly in scope
      }));
  }, []);

  // Example render by state
  const clubsByState = useMemo(() => {
    return clubs.reduce<Record<string, typeof clubsRaw>>((acc, club) => {
      if (!acc[club.state]) acc[club.state] = [];
      acc[club.state].push(club);
      return acc;
    }, {});
  }, [clubs]);

  return (
    <div className="App">
      <h1>Australian Square Dance Clubs</h1>
      {Object.entries(clubsByState).map(([state, stateClubs]) => (
        <div key={state}>
          <h2>{state}</h2>
          <ul>
            {stateClubs.map((club) => (
              <li key={club.id}>
                <img
                  src={club.logo}
                  alt={`${club.name} logo`}
                  width={50}
                  height={50}
                />{" "}
                {club.name} - {club.city}
              </li>
            ))}
          </ul>
        </div>
      ))}
    </div>
  );
};

export default App;